### ISSUE TITLE
Estimated range of IR transmitters?

### ISSUE THREAD

**Issue by mike-mo** [AnaviTechnology/anavi-infrared#4]
I'm interested in this hat, but I haven't been able to locate information on the typical range you can expect to get from it. Do you have any guide numbers for it? Thanks

**Comment by leon-anavi** [comment]
Hi @mike-mo,

The range depends on the environment and on many circumstances therefore it is hard to say at exact distance. The typical range is greater than the one on most remote controls because ANAVI Infrared pHAT has 2 IR LEDs (instead of just one as in most remote controls). Direct visibility is required. Works perfectly fine in range of about 3-4meters. In an appropriate setup the range could be far more than this.

Best regards,
Leon

**Comment by mike-mo** [comment]
Thanks, Leon!
